# the envioronment file is there for set up the github actions
name: myenv
channels:
  - conda-forge
# dependencies obviuly says what base programs that the action needs to run
dependencies:
  - python=3.11
  - pip
# in this case the pip followed by all kinds of packages are all the packages that the program needs most if not all of them can also be found in the requirements.txt but it serves a intirly diffrent function 
  - pip:
      - aniso8601==10.0.1
      - attrs==25.4.0
      - blinker==1.9.0
      - click==8.3.0
      - colorama==0.4.6
      - Flask==3.1.2
      - flask-cors==6.0.1
      - Flask-JWT-Extended==4.7.1
      - flask-restx==1.3.2
      - importlib_resources==6.5.2
      - iniconfig==2.3.0
      - itsdangerous==2.2.0
      - Jinja2==3.1.6
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - MarkupSafe==3.0.3
      - mysql==0.0.3
      - mysql-connector-python==9.5.0
      - mysqlclient==2.2.7
      - packaging==25.0
      - pluggy==1.6.0
      - Pygments==2.19.2
      - PyJWT==2.10.1
      - pytest==8.4.2
      - referencing==0.37.0
      - rpds-py==0.27.1
      - typing_extensions==4.15.0
      - Werkzeug==3.1.3
